---
title: "Analysis"
author: "Untitled"
format: pdf
---

```{r echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(ggthemes)
library(tidyr)
library(knitr)
```


```{r warning=FALSE}
beers <- c("Sierra(Pale_ale)", "Coors(Generic)", "Guinness(Dark)", "Pliny(IPA)")
Nolan <- c(NA, 6, 5.5, 3)
Jon <- c(5.5, 6, 3.5, NA)
Benni <- c(7, NA, 4, 8.5)
Zach <- c(2.5, 6.5, NA, 2)

raw_data <- data.frame(beers, Nolan, Jon, Benni, Zach)

pivoted_raw_data <- pivot_longer(raw_data,
                        cols=-beers,
                        names_to = "names",
                        values_to = "rating")

cleaned_data <- pivoted_raw_data %>% 
  drop_na(rating)

cleaned_data

cleaned_data$rating

mean(cleaned_data$rating)
```

```{r}
model <- lm(rating~beers+names,
             data = cleaned_data)
resid <- residuals(model)
```


```{r}
anova(model)
```

```{r}
shapiro.test(resid)
```

```{r}
cleaned_data %>% 
  ggplot(aes(x = rating,
             y = beers))+
  geom_point(size = 2)+
  theme_few()+
  ggtitle("Ratings Per Beer")+
  ylab("Type of Beer")+
  xlab("Rating")
```



```{r}
cleaned_data %>% 
  ggplot(aes(x = rating,
             y = names))+
  geom_point(size = 2)+
  theme_few()+
  ggtitle("Rating Per Subject")+
  xlab("Subjects")+
  ylab("Rating")
```

```{r}
library(lme4)
library(lmerTest)

model <- lmer(rating ~ beers + (1 | names), data = cleaned_data)
```

```{r}
summary(model)
```
```{r}
raw_data %>%
  kable(
    caption = "Beer Ratings by Participant",
    col.names = c("Beers", "Nolan", "Jon", "Benni", "Zach"),
    align = "c"
  )
```

```{r}
anove_object <- anova(model)

anove_object %>% 
  kable
```


